out_dir: /data/jhmun0206/results/ellipticpp_gcn

dataset:
  name: ellipticpp
  dir: /data/jhmun0206/datasets/ellipticpp
  format: PyG
  task: node
  task_type: classification
  node_encoder: False
  edge_encoder: False

model:
  type: gnn
  loss_fun: cross_entropy

gnn:
  layer_type: generalconv
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 128
  dropout: 0.1
  batch_norm: True
  residual: True
  head: node
  l2norm: True
  act: relu

train:
  mode: standard
  batch_size: 1
  sampler: full_batch
  eval_period: 1
  enable_ckpt: True
  ckpt_best: True

val:
  sampler: full_batch

optim:
  optimizer: adam
  base_lr: 0.001
  weight_decay: 0.0001
  max_epoch: 50
  scheduler: cos

num_workers: 0
seed: 0
device: cuda
print: both
metric_best: f1
metric_agg: argmax
