out_dir: /data/jhmun0206/results/fraudgt/ellipticpp

dataset:
  name: ellipticpp
  dir: /local_datasets/ellipticpp
  format: pyg
  split: [1.0, 0.0, 0.0]   # ğŸ‘ˆ ì „ë¶€ trainìœ¼ë¡œë§Œ
  split_mode: standard
  split_index: 0
  task: node
  task_type: classification

model:
  type: mlp           # run_ellipticpp.pyì—ì„œ ìš°ë¦¬ê°€ ë“±ë¡í•œ MLP

optim:
  optimizer: adam
  base_lr: 0.001
  weight_decay: 0.0001
  max_epoch: 5

train:
  mode: custom
  batch_size: 64      # ë„ˆ ë°ì´í„° í¬ë©´ ì—¬ê¸° ì¡°ì ˆ
  eval_period: 1
  skip_train_eval: False

val:
  sampler: full_batch
