out_dir: /data/jhmun0206/results/fraudgt/ellipticpp_hgt

dataset:
  name: ellipticpp
  dir: /data/jhmun0206/datasets/ellipticpp
  format: pyg
  task: node
  task_type: classification
  split: [0.8, 0.1, 0.1]
  split_mode: standard
  to_undirected: True

share:
  dim_in: 183
  dim_out: 3
  num_splits: 1

model:
  type: gnn
  loss_fun: cross_entropy

gnn:
  layer_type: hgt
  dim_inner: 128
  layers_pre_mp: 0
  layers_mp: 2
  layers_post_mp: 1
  batch_norm: True
  residual: True
  dropout: 0.2
  head: node
  l2norm: True
  clear_feature: False

train:
  mode: custom
  batch_size: 2048
  sampler: full_batch
  eval_period: 1
  enable_ckpt: True
  ckpt_best: True

optim:
  optimizer: adam
  base_lr: 0.001
  weight_decay: 0.0001
  max_epoch: 50
  scheduler: cos

seed: 0
device: cuda
print: both
metric_best: auto
metric_agg: argmax